### ISSUE TITLE
Support for short version output (i.e. v1 and v1.2)

### ISSUE THREAD

**Issue by dmerrick** [battila7/get-version-action#5]
In addition to `version`, it would be nice to have outputs for the shorter version numbers.

For example:

* `version` -> `v1.2.3`
* `minor-version` -> `v1.2`
* `major-version` -> `v1`

This is helpful when tagging Docker images but would probably be useful in other situations too.

Thanks!

**Comment by battila7** [comment]
Hi,

sure, this one looks like a great idea! Based on my current schedule, I can fit this in the following week and then release it on the  `v2` branch being a non-breaking change.

**Comment by battila7** [comment]
@dmerrick

Support has landed on the `v2` branch or you can use the `v2.2.0` tag alternatively.

Please refer to the README regarding the new outputs.

Thanks again for opening this issue, I hope, this new feature is going to be useful for you and others as well 💯

**Comment by dmerrick** [comment]
Thank you, this worked perfectly
